parameters:
- name: SUBSCRIPTION_ID
  type: string
- name: RESOURCE_GROUP_NAME
  type: string
- name: WORKSPACE_NAME
  type: string
- name: DATA_PATH
  type: string
- name: DATASET_NAME
  type: string
- name: DATASET_DESC
  type: string

steps:
  - task: AzureCLI@2
    displayName: Register Data Asset
    continueOnError: false
    env: {APPLICATIONINSIGHTS_CONNECTION_STRING: "$(APPLICATIONINSIGHTS-CONNECTION-STRING)"}
    inputs: 
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: |
        ${{parameters.script_parameter}}